### ISSUE TITLE
json-logger library(version 1.0.2) gives no class def found error.

### ISSUE THREAD

**Issue by vijayaratha** [mulesoft-consulting/json-logger#12]
when using json-logger library as a dependency for the API in mule 4 (anypoint studio, it gives

No call def found error for google common cache library. If I remove the json-logger library dependency, my project gets deployed successfully. I have posted detail error stack and finding here[1]

[1]https://stackoverflow.com/questions/60033243/mule-application-in-anypoint-studio-throws-caused-by-java-lang-classnotfoundexc/60068499?noredirect=1#comment106251454_60068499

```
Caused by: org.mule.runtime.module.artifact.api.classloader.exception.CompositeClassNotFoundException: Cannot load class 'com.google.common.cache.CacheLoader': [
	com.google.common.cache.CacheLoader, 
	Cannot load class 'com.google.common.cache.CacheLoader': [
	Class 'com.google.common.cache.CacheLoader' has no package mapping for region 'domain/default/app/delwp-api-mule-hr-admin-api-v1'., 
	Cannot load class 'com.google.common.cache.CacheLoader': [
	com.google.common.cache.CacheLoader, 
	Class 'com.google.common.cache.CacheLoader' not found in classloader for artifact 'container'.]]]
Caused by: java.lang.ClassNotFoundException: com.google.common.cache.CacheLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at org.mule.runtime.module.artifact.api.classloader.FineGrainedControlClassLoader.findLocalClass(FineGrainedControlClassLoader.java:167) ~[mule-module-artifact-4.1.3.jar:4.1.3]
	at org.mule.runtime.module.artifact.api.classloader.FineGrainedControlClassLoader.loadClass(FineGrainedControlClassLoader.java:84) ~[mule-module-artifact-4.1.3.jar:4.1.3]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
```

**Comment by vijayaratha** [comment]
Any clue on this? How can i overcome? Is it an issue in library packaging or in mule runtime settings?
